// Food
export const FETCH_FOOD_LIST = 'FETCH_FOOD_LIST';
export const FETCH_FOOD_DETAIL = 'FETCH_FOOD_DETAIL';
// Seoul
// Recipe
export const FETCH_RECIPE_LIST = 'FETCH_RECIPE_LIST';
export const FETCH_RECIPE_DETAIL = 'FETCH_RECIPE_DETAIL';
export const FETCH_RECIPE_FIND = 'FETCH_RECIPE_FIND';
// Board
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST';
export const FETCH_BOARD_DETAIL = 'FETCH_BOARD_DETAIL';
export const FETCH_BOARD_UPDATE = 'FETCH_BOARD_UPDATE';
export const FETCH_BOARD_DELETE = 'FETCH_BOARD_DELETE';
export const FETCH_BOARD_UPDATE_OK = 'FETCH_BOARD_UPDATE_OK';
export const FETCH_BOARD_INSERT = 'FETCH_BOARD_INSERT';

export const RESET = 'RESET';